// GENERATED by `node tools/music.mjs calibrate --voices`. Do not edit by hand.
// VOCAB_ALT_TRIM: per style, slot and alternate, the gain trim (dB) that brings the alternate to the
// slot's stem target (the style's number plus its VOCAB_TARGET_FIX) on the neutral test phrase.
// INST_LEVEL: each instrument's stem level (dB, the stem meter) at gainDb 0 playing a slot's test line
// (cinematic test signal, counter line an octave down; drums on the lo-fi electronic kit; default options):
// a composer's own voice is placed at the slot's target from it, so its gainDb is an offset from
// calibrated, like `levels`. VOCAB_ALT_TARGET_FIX: where a 30 dB trim cannot reach the target, the
// target moves to where the alternate sits. INST_REGISTER: each instrument's level against the lead
// line moved by octaves ([median MIDI pitch, dB vs its lead level]); SLOT_REF_PITCH: the median pitch
// of each slot's test line. Your own voice is placed for the register it actually plays in.
import type { Slot } from "./vocab";
export const VOCAB_ALT_TRIM: Record<string, Partial<Record<Slot, Record<string, number>>>> = {
 lofiElectronic: {
  lead: {
   bell: 2.6,
   mallet: 2.6,
   guitar: 16.3
  },
  chords: {
   strings: 4.6,
   piano: 24.7
  },
  bass: {
   warm: -1.5
  }
 },
 drive: {
  lead: {
   pluck: -0.9
  },
  bass: {
   sub: 1.7
  }
 },
 cinematic: {
  lead: {
   piano: 10.4,
   bell: 5.3,
   celesta: 1.9
  },
  counter: {
   piano: 30
  }
 },
 ambient: {
  lead: {
   pluck: -1.8,
   vibes: 2
  }
 },
 folk: {
  lead: {
   piano: 13.1,
   guitar: 18.1,
   strings: 13.5
  },
  chords: {
   strings: 2.7
  }
 },
 playful: {
  lead: {
   chip: 14.5,
   pluck: 3.6,
   bell: 6.3
  },
  bass: {
   tuba: -1.7
  }
 },
 musicBox: {
  lead: {
   celesta: 2.9,
   bell: 6.2
  }
 },
 nocturne: {},
 minimalist: {
  arp: {
   piano: 22.5,
   pluck: 2.2
  }
 },
 jazz: {
  lead: {
   piano: 12.7,
   clarinet: 11.5,
   flute: 11.2,
   brass: 17.8
  }
 },
 lullaby: {
  lead: {
   musicBox: 5.2,
   piano: 14.2,
   flute: 11.1
  }
 },
 chiptune: {
  lead: {
   square: 8.1
  }
 },
 lofi: {
  lead: {
   guitar: 17.1,
   flute: 11.3
  }
 },
 orchestral: {
  lead: {
   strings: 10.8,
   horn: 17.1,
   flute: 13.1
  },
  counter: {
   flute: 6.7,
   harp: 11.2
  }
 },
 suspense: {
  counter: {
   choir: 8.8,
   bell: 19
  },
  lead: {
   choir: -2.2,
   cello: 8.2
  }
 },
 rock: {
  chords: {
   strings: 10.8,
   organ: 19.2,
   piano: 27
  },
  lead: {
   guitar: -2
  }
 },
 hipHop: {
  lead: {
   bell: 2.9,
   flute: 8.7,
   choir: 3.6
  },
  chords: {
   pad: -6.3
  }
 },
 house: {
  chords: {
   pad: 4.8,
   piano: 25.6
  },
  lead: {
   synth: 14.6
  }
 },
 synthwave: {
  chords: {
   pad: 1.7
  },
  lead: {
   brass: 13.4
  }
 },
 world: {
  lead: {
   pluck: 17,
   marimba: 4.1,
   reed: 9.8,
   bowed: 12.7
  }
 },
 choral: {
  chords: {
   organ: 4,
   strings: 4.1
  },
  lead: {
   bowed: 10.3,
   flute: 9.1
  }
 }
};
export const VOCAB_ALT_TARGET_FIX: Record<string, Partial<Record<Slot, Record<string, number>>>> = {
 cinematic: {
  counter: {
   piano: -9.1
  }
 }
};
export const INST_LEVEL: Record<string, Partial<Record<Slot, number>>> = {
 piano: {
  chords: -41,
  lead: -27.4,
  counter: -45.4,
  bass: -31.1,
  arp: -39.8
 },
 musicBox: {
  chords: -22.9,
  lead: -19.8,
  counter: -28.8,
  bass: -25.1,
  arp: -23.8
 },
 bell: {
  chords: -12.6,
  lead: -9.6,
  counter: -18.6,
  bass: -12.2,
  arp: -12
 },
 celesta: {
  chords: -20.1,
  lead: -18.9,
  counter: -27,
  bass: -20,
  arp: -20.2
 },
 marimba: {
  chords: -20.8,
  lead: -20.3,
  counter: -32.5,
  bass: -19.3,
  arp: -20.5
 },
 vibes: {
  chords: -20.4,
  lead: -18.3,
  counter: -26.3,
  bass: -18.6,
  arp: -19.4
 },
 harp: {
  chords: -32.5,
  lead: -30.9,
  counter: -39.1,
  bass: -33.8,
  arp: -30.9
 },
 guitar: {
  chords: -32.1,
  lead: -34,
  counter: -38.9,
  bass: -33.4,
  arp: -34.7
 },
 strings: {
  chords: -20.5,
  lead: -26.4,
  counter: -30.3,
  bass: -25.7,
  arp: -28.3
 },
 fmBell: {
  chords: -22.3,
  lead: -18.3,
  counter: -27.7,
  bass: -21.3,
  arp: -20.1
 },
 ePiano: {
  chords: -22.1,
  lead: -23.3,
  counter: -32.7,
  bass: -21.2,
  arp: -24.3
 },
 pulse: {
  chords: -21.5,
  lead: -23.9,
  counter: -28.4,
  bass: -24.4,
  arp: -26.4
 },
 triangle: {
  chords: -13.5,
  lead: -18.2,
  counter: -18.3,
  bass: -18.3,
  arp: -18.3
 },
 noiseDrum: {
  kick: -25.5,
  snare: -27.1,
  hat: -41.6
 },
 kick: {
  kick: -12.1,
  snare: -25.6,
  hat: -44.1
 },
 snare: {
  kick: -12.1,
  snare: -25.6,
  hat: -44.1
 },
 hat: {
  kick: -12.1,
  snare: -25.6,
  hat: -44.1
 },
 bass: {
  chords: -12.6,
  lead: -13.9,
  counter: -17.8,
  bass: -15.2,
  arp: -14.6
 },
 warmPad: {
  chords: -21.8,
  lead: -29,
  counter: -30.9,
  bass: -23.8,
  arp: -30.8
 },
 softPluck: {
  chords: -22.2,
  lead: -20.1,
  counter: -29.7,
  bass: -25.6,
  arp: -21.6
 },
 sub: {
  chords: -25.5,
  lead: -39.8,
  counter: -46.5,
  bass: -12.9,
  arp: -30.9
 },
 organ: {
  chords: -30.8,
  lead: -35.3,
  counter: -38.3,
  bass: -35.1,
  arp: -37.7
 },
 brass: {
  chords: -22.7,
  lead: -27.2,
  counter: -32.2,
  bass: -22.1,
  arp: -30.2
 },
 woodwind: {
  chords: -20,
  lead: -24.1,
  counter: -26.6,
  bass: -23,
  arp: -25.9
 },
 choir: {
  chords: -10.8,
  lead: -19.7,
  counter: -18.1,
  bass: -21.8,
  arp: -17.2
 },
 timpani: {
  kick: -13.4,
  snare: -15,
  hat: -16.5
 },
 leadSynth: {
  chords: -29.6,
  lead: -29,
  counter: -33.2,
  bass: -28.1,
  arp: -31.5
 },
 bowedSolo: {
  chords: -20.2,
  lead: -27.2,
  counter: -31.3,
  bass: -27.3,
  arp: -25.7
 },
 glockenspiel: {
  chords: -22.4,
  lead: -19.1,
  counter: -27.8,
  bass: -21.4,
  arp: -21.4
 },
 wurlitzer: {
  chords: -25.5,
  lead: -28.6,
  counter: -35.9,
  bass: -22.9,
  arp: -31.3
 },
 pipeOrgan: {
  chords: -20,
  lead: -25,
  counter: -25.6,
  bass: -24.4,
  arp: -26
 }
};
export const INST_REGISTER: Record<string, [number, number][]> = {"piano":[[44,5.5],[56,5.3],[68,3.9],[80,0],[92,-5.6],[104,-12.3]],"musicBox":[[44,0.4],[56,0.2],[68,0.2],[80,0],[92,-2.1],[104,-4.7]],"bell":[[44,2.1],[56,1.9],[68,1.1],[80,0],[92,-1.4],[104,-3.1]],"celesta":[[44,2.7],[56,2.7],[68,1.3],[80,0],[92,-2.3],[104,-4.8]],"marimba":[[44,7],[56,5.5],[68,2.7],[80,0],[92,-3.8],[104,-7]],"vibes":[[44,2.2],[56,2.6],[68,1.5],[80,0],[92,-1.4],[104,-2.4]],"harp":[[44,3.8],[56,3.6],[68,3.6],[80,0],[92,0.1],[104,0.8]],"guitar":[[44,4.3],[56,4.7],[68,3],[80,0],[92,-0.4],[104,-3.3]],"strings":[[44,-2.4],[56,1],[68,0.8],[80,0],[92,-4.2],[104,-8.3]],"fmBell":[[44,3],[56,2.3],[68,1],[80,0],[92,-1.3],[104,-2.1]],"ePiano":[[44,3.9],[56,4.8],[68,2.9],[80,0],[92,-3.3],[104,-6]],"pulse":[[44,-0.9],[56,-0.4],[68,-0.1],[80,0],[92,-0.2],[104,-1.1]],"triangle":[[44,0],[56,0],[68,0],[80,0],[92,0],[104,-0.2]],"bass":[[44,2.3],[56,2.4],[68,2.3],[80,0],[92,-0.9],[104,-8.8]],"warmPad":[[44,0.4],[56,1.4],[68,1.3],[80,0],[92,-4],[104,-12.2]],"softPluck":[[44,0.1],[56,0.7],[68,1.1],[80,0],[92,-2],[104,-6.1]],"sub":[[44,25.7],[56,21.1],[68,11.5],[80,0],[92,-11.8],[104,-23.2]],"organ":[[44,-1.6],[56,-0.7],[68,-0.1],[80,0],[92,-0.5],[104,-0.7]],"brass":[[44,-0.2],[56,1.5],[68,1.1],[80,0],[92,-0.8],[104,-3.5]],"woodwind":[[44,-0.4],[56,0.2],[68,0.2],[80,0],[92,-0.2],[104,-0.1]],"choir":[[44,-2.9],[56,0.8],[68,4.5],[80,0],[92,-0.3],[104,4]],"leadSynth":[[44,-1.3],[56,-0.7],[68,-0.2],[80,0],[92,-1.2],[104,-6.2]],"bowedSolo":[[44,0.2],[56,1.8],[68,3.6],[80,0],[92,-7.6],[104,-30.6]],"glockenspiel":[[44,1.7],[56,1.8],[68,0.8],[80,0],[92,-1.3],[104,-2.3]],"wurlitzer":[[44,7],[56,5.1],[68,2.4],[80,0],[92,-3.7],[104,-6.8]],"pipeOrgan":[[44,-1.6],[56,-0.7],[68,-0.2],[80,0],[92,-0.5],[104,-3.1]]};
export const SLOT_REF_PITCH: Partial<Record<Slot, number>> = {
 chords: 68,
 lead: 80,
 counter: 84,
 bass: 43,
 arp: 68
};
