// GENERATED by `node tools/music.mjs calibrate`: per style, the gain trim (dB) that brings each palette
// voice's stem to its target on a neutral test phrase (stem meter v2: mid, gated). Calibrated (listened) styles keep their targets and get trims only; legacy scores never take a trim.
import type { Slot } from "./vocab";
export const VOCAB_TRIM: Record<string, Partial<Record<Slot, number>>> = {
 lofiElectronic: {
  chords: 2.4,
  lead: -1.1,
  counter: 5.5,
  bass: 0.4,
  kick: -3.1,
  snare: -1.6,
  hat: -0.5
 },
 drive: {
  chords: 6.7,
  lead: 10.7,
  counter: 16.8,
  bass: 3,
  kick: -1,
  snare: 6.5,
  arp: 1.8,
  perc: 5.5
 },
 cinematic: {
  chords: 6.1,
  lead: 6.9,
  counter: 18,
  bass: 2.4,
  kick: -1.8,
  arp: 8.5
 },
 ambient: {
  chords: 2.5,
  lead: 1.6,
  counter: 1.2,
  bass: -0.3,
  kick: -3,
  arp: 1.6
 },
 folk: {
  chords: 18,
  lead: 14.7,
  counter: 12.7,
  bass: -1.2,
  kick: -0.5,
  ghost: 8.3,
  arp: 16.5,
  perc: 17.4
 },
 playful: {
  chords: 3.8,
  lead: 4,
  counter: 12.8,
  bass: -1.4,
  kick: -1.8,
  snare: 3.2,
  hat: 10.3,
  arp: 13.3,
  perc: 11.5
 },
 musicBox: {
  chords: 2.3,
  lead: 2.9,
  counter: 5,
  bass: 6.3,
  arp: 3.9
 },
 nocturne: {
  chords: 17.7,
  lead: 14.1,
  counter: 14.6,
  bass: 6.5
 },
 minimalist: {
  chords: 18,
  lead: 4,
  counter: 15.9,
  bass: -4.3,
  arp: 3.1
 },
 jazz: {
  chords: 18,
  lead: 3.5,
  counter: 12.7,
  bass: -2,
  kick: 0.2,
  ghost: 10,
  hat: 17.2,
  perc: 8.5
 },
 lullaby: {
  chords: 4,
  lead: 4.7,
  counter: 18,
  bass: 13,
  arp: 16.4
 },
 chiptune: {
  lead: 7.4,
  bass: -0.7,
  kick: 9.2,
  snare: 10.7,
  arp: 13.2
 },
 lofi: {
  chords: 9.3,
  lead: 3.6,
  counter: 18,
  bass: -0.5,
  kick: 0.2,
  snare: 5.2,
  ghost: 14.5,
  hat: 18
 },
 orchestral: {
  chords: 4.5,
  lead: 14.7,
  counter: 0,
  bass: 2.4,
  kick: -5.6,
  snare: 5.3,
  arp: 7.7,
  perc: 2.9
 },
 suspense: {
  chords: 5.8,
  lead: 7.2,
  counter: 13.5,
  bass: 0,
  kick: -0.3,
  arp: 8.9,
  perc: 8.2
 },
 rock: {
  chords: 11.5,
  lead: 11.9,
  counter: 18,
  bass: 0.7,
  kick: -1,
  snare: 5.8,
  hat: 8.4,
  perc: 5.7
 },
 hipHop: {
  chords: 18,
  lead: -1.1,
  counter: 17.6,
  bass: 1.6,
  kick: -2.7,
  snare: 5.7,
  hat: 9.2,
  perc: 7.7
 },
 house: {
  chords: 12.7,
  lead: -0.7,
  counter: 11.5,
  bass: 3.5,
  kick: 0.3,
  snare: 4.8,
  arp: 2,
  perc: 4.1
 },
 synthwave: {
  chords: 4.9,
  lead: 11.7,
  counter: 16.7,
  bass: 2.8,
  kick: 1.2,
  snare: 4.3,
  arp: 1.2,
  perc: 3.5
 },
 world: {
  chords: 4.9,
  lead: 9.5,
  counter: 18,
  bass: -1.5,
  kick: 0.5,
  ghost: 12.5,
  arp: 16.7
 },
 choral: {
  chords: -7.7,
  lead: -3.8,
  counter: 16.8,
  bass: 9.6,
  arp: 14,
  perc: 9.2
 }
};
/** Where an 18 dB trim could not reach the target (long-decaying plucks read low as active RMS), the target moves to where the voice sits. */
export const VOCAB_TARGET_FIX: Record<string, Partial<Record<Slot, number>>> = {
 lofiElectronic: {},
 drive: {},
 cinematic: {
  counter: -8.9
 },
 ambient: {},
 folk: {
  chords: -6.5
 },
 playful: {},
 musicBox: {},
 nocturne: {},
 minimalist: {
  chords: -4.6
 },
 jazz: {
  chords: -4
 },
 lullaby: {
  counter: -1.2
 },
 chiptune: {},
 lofi: {
  counter: -2.4,
  hat: -6.3
 },
 orchestral: {},
 suspense: {},
 rock: {
  counter: -8.6
 },
 hipHop: {
  chords: -9.4
 },
 house: {},
 synthwave: {},
 world: {
  counter: -10.7
 },
 choral: {}
};
