# notes/make_cues.py: notes/cues.json -> src/canvas-core/cues.ts (seconds x 24, rounded)
import json
c = json.load(open('notes/cues.json'))
rows = ",\n".join(f"  [{round(x['start'] * 24)}, {round(x['end'] * 24)}, {json.dumps(x['text'])}]" for x in c)
open('src/canvas-core/cues.ts', 'w').write(
    "// Generated by notes/make_cues.py from notes/cues.json. Do not edit by hand.\n"
    "// [startFrame, endFrame, text] at 24 fps, aligned to voiceover.mp3's pauses (notes/align.py).\n"
    f"export const CUES: [number, number, string][] = [\n{rows},\n];\n")
